/**
 * Additional environment variable types not generated by wrangler.
 * These are typically secrets stored in .dev.vars or Cloudflare dashboard.
 */

declare global {
  interface Env {
    /** Anthropic API key for Claude agents. Set in .dev.vars or as Cloudflare secret. */
    ANTHROPIC_API_KEY?: string;
  }
}

export {};
